### ISSUE TITLE
Move titlelize util for GP Surgery names in the ETL

### ISSUE THREAD

**Issue by beseven** [nhsuk/gp-data-etl#10]
The current code and tests for the GP Surgery name manipulation is in 

https://github.com/nhsuk/gp-finder/blob/master/app/lib/utils/properCapitalize.js
https://github.com/nhsuk/gp-finder/blob/master/test/unit/lib/utils/properCapitalize.js

This should be handled in the ETL

**Comment by st3v3nhunt** [comment]
This is now done
